name: GitHub Actions - Cron Job Template
run-name: Running - ${{ github.event_name }}
on:
  schedule:
    # exemplo para ser executado as 21h45
    - cron: '45 21 * * *'

    

jobs:
  on-workflow_dispatch:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "Comentário Cron Job"