name: GitHub Actions - Push - Branch Template
run-name: Running - ${{github.event_name}}
on:
    push:
        branches:
            - main
            - develop
            - 'relase/**'

jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: Comentário
              run: |
                echo "Exemplo usando on push branches"