name: GitHub Actions - Pull - Branch Template
run-name: Running - ${{github.event_name}}
on:
    pull_request:
        branches:
            - main
jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
        -   name: Comentário
            run: |
                echo "Comentário PULL REQUEST WORKFLOW - branch"