name: Github Actions - Workflow dispatch Template - Booleano
run-name: Running - ${{github.event_name}}
on:
    workflow_dispatch: 
        inputs:
            severidade:
                description: funcionalidade crítica?
                type: boolean
jobs:
    on-workflow_dispatch:
        runs-on: ubuntu-latest
        steps:
        -   name: Comentário
            run: |
                    echo "Comentário Workflow dispatch - Boolean: ${{inputs.severidade}}"
